### ISSUE TITLE
Interfaz

### ISSUE THREAD

**Issue by marreA** [CC-ULL/TSP_Intensification_2#3]
Cito el contenido del siguiente enlace [3-OPT TSP](https://en.wikipedia.org/wiki/3-opt) : 
 > 3-opt analysis involves deleting 3 connections (or edges) in a network (or tour), reconnecting the network in all other possible ways, and then evaluating each reconnection method to find the optimum one. This process is then repeated for a different set of 3 connections

Tenemos que aplicar una búsqueda local intercambiando tres conexiones cuantas veces sea posible. Para ello necesitamos acceder al vector **succ** y comprobar el camino que se presenta en la solución, pero no se proporciona ningún método en la clase **[TSP_sol_t](https://github.com/CC-ULL/TSP_common/blob/master/TSP_sol_t.hpp)** para realizar esta acción.
Del mismo modo sería conveniente tener acceso a un método que evalué el coste de un camino y que sea común a todas las implementaciones de **Intensification** .  @jrieraledesma

**Comment by jrieraledesma** [comment]
Eso significa que tienes que construir el vector succ a partir un objeto TSP_sol_t. No tiene que se un método vinculado a esta clase, sino uno específico del procedimiento 3-OPT. También está muy bien pensado el segundo método para evaluar el camino. Se trata de procedimientos auxiliares que tendréis que desarrollar alrededor del 3-OPT. Si creas una clase 3-opt_t pueden ser métodos de la clase. @CC-ULL/equipo-3

**Comment by jrieraledesma** [comment]
En suma, una sugerencia sería crear una clase 3opt_t que contuviera una referencia constante a TSP_sol_t y a TSP_input_t, incluir los métodos específicos que has mencionado como métodos privados. @CC-ULL/equipo-3

**Comment by jrieraledesma** [comment]
Quizá un enfoque más interesante y más general sería crear una clase que contenga una referencia constante a la entrada, ya que vamos a necesitar esa información para cualquier solución factible a la que vayamos a aplicar el 3opt. También se creará una estructura de datos auxiliar parecida a la lista de adyacencia que permita establecer los sucesores y que será construida en el constructor. En esta clase añadiremos dos métodos que nos permitan saber los sucesores de un elemento.

Necesitaría saber si te refieres al sucesor en una solución factible, o  a los potenciales sucesores de un vértices.

Por otro lado podríamos crear un método que evalúe un camino. No sé exactamente en qué condiciones lo necesitáis, necesitaría más detalles.

Haríamos un método, si queréis un método main, que reciba la solución factible (una referencia constante),  y que entregue por referencia la solución mejorada. @CC-ULL/equipo-3
